[package]
name = "pasties"
description = "HTML pastebin and static site host "
version = "0.1.0"
edition = "2024"
repository = "https://github.com/mellowcoffee/pasties"
homepage = "https://github.com/mellowcoffee/pasties"
readme = "readme.md"
license = "AGPL-3.0-or-later"

[dependencies]
ammonia = "4.1.3"
anyhow = "1.0.103"
argon2 = "0.5.3"
axum = "0.8.9"
base64 = "0.22.1"
chrono = "0.4.45"
maud = { version = "0.27.0", features = [ "axum" ] }
paste = "1.0.15"
rand = "0.10.2"
regex = "1.13.0"
serde = "1.0.228"
serde_valid = "2.0.3"
sha2 = "0.11.0"
snof = { git = "https://github.com/mellowcoffee/snof.git" }
sqlx = { version = "0.8.6", features = [ "runtime-tokio", "postgres", "chrono" ] }
thiserror = "2.0.18"
tokio = { version = "1.52.3", features = [ "rt", "rt-multi-thread", "macros" ]}
toml = "1.1.2"
url = "2.5.8"

[lints.rust]
rust_2018_idioms = { level = "warn", priority = -1 }
unused = { level = "warn", priority = -1 }

unsafe_code = "forbid"

let-underscore = "warn"
missing_debug_implementations = "warn"
nonstandard-style = "warn"

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }

multiple_crate_versions = "allow"
missing_const_for_fn = "allow"
cargo_common_metadata = "allow"
equatable_if_let = "allow"
manual_let_else = "allow"

unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
todo = "warn"
dbg_macro = "warn"
print_stdout = "warn"
undocumented_unsafe_blocks = "warn"
mem_forget = "deny"
exit = "warn"
rest_pat_in_fully_bound_structs = "warn"
verbose_file_reads = "warn"
str_to_string = "warn"
implicit_clone = "warn"
